### ISSUE TITLE
API Documentation and Links

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#49]
We require better documentation for integration with the OpenNEM API and using the Python client library with examples.

Open issue here for tracking tasks / progress on improving documentation and onboarding API integrations

## Tasks

 - [x] Link the API generated docs from homepage / developer docs
 - [x] Link OpenAPI schema 
 - [ ] Better developer landing page (`developers.opennem.org.au`) with overview
 - [ ] Link to CC license / terms
 - [ ] More examples of API integrations and using client library

**Comment by paulculmsee** [comment]
@nc9 I am creating an [independent publisher connector](https://github.com/paulculmsee/PowerPlatformConnectors/tree/dev/independent-publisher-connectors) for this API to be accessible from Microsoft's Power Platform which hopefully might expose it to a new audience. Would this fit into the "more examples" category? Or maybe another section?

**Comment by nc9** [comment]
This sounds great - if you can get it together we’ll work out a way to promote it. We also need to do a better job of promoting our own Python client and the various notebooks we have as examples

**Comment by paulculmsee** [comment]
I've submitted my Power Platform connector for OpenNEM, Microsoft are now going through a certification process but once done OpenNEM will be available to anyone in the world who wants to integrate this data into an app or a Power Automate flow. Time to discuss perhaps

**Comment by nc9** [comment]
@paulculmsee that's awesome - great to hear!

**Comment by paulculmsee** [comment]
@nc9 Microsoft have confirmed the connector will be available world-wide within 3 weeks. 

![image](https://user-images.githubusercontent.com/4979626/149063499-eba336f4-541a-48c2-868b-de97c2901d62.png)

I'll make some noise about it when that happens

**Comment by nc9** [comment]
https://docs.openelectricity.org.au/
